---
- hosts: localhost

  tasks:
  - name: install afl
    become: yes
    apt:
      name:
        - git
        - afl
        - afl-cov
        - afl-clang
        - python-pip
        - clang
        - build-essential
  - name: clone afl-utils
    git:
      repo: https://github.com/rc0r/afl-utils
      dest: /home/collin/afl-utils
  - name: install afl-utils
    become: yes
    command: pip3 install .
    args:
      chdir: /home/collin/afl-utils
  - name: clone afl-kit
    git:
      repo: https://github.com/kcwu/afl-kit
      dest: /home/collin/afl-kit
  - name: setup afl-kit dependencies
    become: yes
    pip:
      name: tqdm
  - name: install new afl-cmin
    become: yes
    command: cp afl-cmin.py /usr/bin/afl-cmin
    args:
      chdir: /home/collin/afl-kit
